import random
colorlist = [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40
             ,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77]

runelist = [ 0x4537389E,0x41F8635E,0x454DBB41,0x454DBB43] 
w =random.choice(runelist)           
while not Player.IsGhost:
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    w =random.choice(runelist)
    Target.TargetExecute(w)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    w =random.choice(runelist)
    Target.TargetExecute(w)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    w =random.choice(runelist)
    Target.TargetExecute(w)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    w =random.choice(runelist)
    Target.TargetExecute(w)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    
