import random
colorlist = (range(1,255))

while not Player.IsGhost:
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    Target.TargetExecute(0x4537389E)
    Misc.Pause(3250)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    Target.TargetExecute(0x41F8635E)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    Target.TargetExecute(0x454DBB41)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Spells.CastMagery('Gate Travel')
    Target.WaitForTarget(10000,False)
    Misc.Pause(200)
    Target.TargetExecute(0x454DBB42)
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(3250)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(7500)
    x=random.choice(colorlist)
    Player.ChatSay(x,'$$$.dps Shop , Guarded$$$')
    Misc.Pause(2000)
    if Target.GetTargetFromList('clients'):
        Player.ChatSay(27,'Greetings Traveler')
